---
# ansible-playbook --ask-vault-pass -v play_add_user.yaml

- name: add user for basic authentication in apache
  hosts: all
  become: yes
  vars_prompt:
    - name: username
      prompt: "username"
      private: no
    - name: userpassword
      prompt: "userpassword"
    - name: gitolite_user
      prompt: "gitolite user name"
      default: "git"
      private: no
    - name: gitolite_home
      prompt: "path to the gitolite home directory (repositories are stored here)"
      default: "/data/gitolite"
      private: no
  tasks:
    - include: task_riaf_add_user.yaml
