# https://docs.ansible.com/ansible/2.5/modules/apt_module.html

- name: update cache
  apt:
    force_apt_get: yes
    update_cache: yes
- name: install necessary tools
  apt:
    name:
      - apache2
      - apache2-suexec-custom
      - git
      - git-annex
      - gitolite3
      - python3-dulwich
      - python3-fusepy
      - python3-pip
      - python3-setuptools
    state: present
    force_apt_get: yes
