#!/bin/sh
passwdfile=/etc/apache2/gitolite.passwd
davusersfile=/data/gitolite/dav_users

if [ ! -f $davusersfile ] || [ $passwdfile -nt $davusersfile ]; then
    cut -d ":" -f 1 $passwdfile > $davusersfile
fi
