#!/bin/sh

cat > openssl-fdm.playground.pa.dlr.de.conf <<EOF
[ req ]   
distinguished_name    = req_distinguished_name
string_mask = nombstr
req_extensions = v3_req
[ req_distinguished_name ]
countryName            = Country Name (2 letter code)
countryName_default        = Country Name (2 letter code)
countryName_min            = 2
countryName_max            = 2
stateOrProvinceName        = State or Province Name (full name)
stateOrProvinceName_default    = State or Province Name (full name)
localityName            = Your City
localityName_default        = Your City
0.organizationName        = Organization Name (eg, company)
0.organizationName_default    = Organization Name (eg, company)
organizationalUnitName        = Organizational Unit Name (eg, section)
organizationalUnitName_default    =  Organizational Unit Name (eg, section)
commonName            = YOUR NAME
commonName_max            = 64
commonName_default        = fdm.playground.pa.dlr.de
emailAddress            = E-MAIL
emailAddress_max        = 64
emailAddress_default        = webmaster@fdm.playground.pa.dlr.de
[ v3_req ]
subjectAltName = @alt_names
[alt_names]
DNS.1 = fdm.playground.pa.dlr.de
EOF
openssl genrsa -out fdm.playground.pa.dlr.de.key 4096
openssl req -new -batch -nodes -sha256 \
	-key  fdm.playground.pa.dlr.de.key \
	-outform PEM -out fdm.playground.pa.dlr.de.csr \
	-config openssl-fdm.playground.pa.dlr.de.conf
rm openssl-fdm.playground.pa.dlr.de.conf  # remove temporary config
openssl req -text -noout -in fdm.playground.pa.dlr.de.csr

echo
echo "You can create a self signed certificate:"
echo "openssl rsa -in fdm.playground.pa.dlr.de.key -out self_cert.key"
echo "openssl x509 -days 365 -in fdm.playground.pa.dlr.de.csr -out fdm.playground.pa.dlr.de.crt -req -signkey self_cert.key"
echo
echo "You should deploy on fdm.playground.pa.dlr.de:"
echo "install -v -m 644 -o root -g root fdm.playground.pa.dlr.de.crt /etc/apache2/ssl.crt/vhost-gitolite.crt"
echo "install -v -m 600 -o root -g root fdm.playground.pa.dlr.de.key /etc/apache2/ssl.key/vhost-gitolite.key"
